FROM ubuntu:latest
WORKDIR /usr/tcp-server

# RUN apt-get update && \
#     apt-get install gcc
# docker run -it -p 8888:8888 -v C:\Users\DaiPhongPC\OneDrive\Desktop\StoringFileProject:/usr/tcp-server --name tcp-img ubuntu:gcc_make