server:
  port: 8888

spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/network
    username: root
    password: lovecan148
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: off

socket:
  host: 127.0.0.1
  port: 8888
  block-size: 1024
file-max-size: 10485760

